#define LOGO_LENGTH 61
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define MENU_MARGIN 3
#define MENU_TOP 0

#define DISPLAY_LINES_3 3
#define DISPLAY_LINES_4 4
#define DISPLAY_LINES_5 5

#define SELECTION_PADDING_L 1
#define SELECTION_WIDTH 120 
#define SELECTION_L_X MENU_MARGIN-1 - SELECTION_PADDING_L-1
#define SELECTION_R_X SELECTION_L_X + SELECTION_WIDTH

// events
#define EVT_SCROLL_UP_END 1
#define EVT_SCROLL_DOWN_END 2

#define SCAN_MODE_AP 1
#define SCAN_MODE_STATIONS 2
#define SCAN_MODE_ALL 3
